import { launchAuditBrowser, resetPage } from './audit-config.mjs'
const browser = await launchAuditBrowser()
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
await resetPage(page)
await page.getByLabel('Email').fill('hr@tracker.demo')
await page.getByLabel('Password').fill('hr2026')
await page.getByRole('button', { name: 'Sign in' }).click()
await page.getByTitle('Open Directory').click()
const manager = page.getByLabel('Reporting manager for Alex Morgan')
await manager.selectOption('maya')
const selected = await manager.inputValue()
console.log(JSON.stringify({ assignmentPersistedInUi: selected === 'maya' }))
await browser.close()
