import { chromium } from 'playwright-core'
const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'}),results=[]
async function test(name,fn){const p=await browser.newPage({viewport:{width:1280,height:900}});p.setDefaultTimeout(2500);try{await p.goto('http://localhost:8000/',{waitUntil:'domcontentloaded',timeout:10000});await p.waitForTimeout(500);await p.evaluate(()=>localStorage.clear());await p.reload({waitUntil:'domcontentloaded',timeout:10000});await p.waitForTimeout(500);await fn(p);results.push(['PASS',name])}catch(e){results.push(['FAIL',name,e.message.split('\n')[0]])}finally{await p.close()}}
const nav=(p,n)=>p.getByRole('button',{name:n,exact:true}).click(),leaveForm=async p=>{await nav(p,'Leave');await p.getByRole('button',{name:'Request leave'}).click()},dates=async p=>{let d=p.locator('input[type=date]');await d.nth(0).fill('2024-12-02');await d.nth(1).fill('2024-12-02')}
await test('Clock in/out',async p=>{await p.getByRole('button',{name:/Clock in/}).click();await p.getByText('Clocked in').waitFor();await p.getByRole('button',{name:/Clock out/}).click();await p.getByText('Clocked out').waitFor()})
await test('Add/edit/delete time entry',async p=>{await nav(p,'Timesheet');await p.getByRole('button',{name:'Add time entry'}).click();await p.locator('input[type=date]').fill('2024-11-25');await p.locator('input[type=time]').nth(0).fill('09:00');await p.locator('input[type=time]').nth(1).fill('10:00');await p.locator('textarea').fill('Test entry');await p.getByRole('button',{name:'Add time entry',exact:true}).click();await p.getByText('Time entry added').waitFor();await p.getByTitle('Edit time entry').last().click();await p.locator('textarea').fill('Edited entry');await p.getByRole('button',{name:'Save changes'}).click();await p.getByText('Edited entry').waitFor();let before=await p.locator('tbody tr').count();await p.getByTitle('Delete time entry').last().click();if(await p.locator('tbody tr').count()!==before-1)throw Error('delete did not remove row')})
for(const [n,fn] of [['full day',async()=>{}],['half day',async p=>p.getByLabel('Half day').check()],['partial hours',async p=>p.locator('input[type=number]').fill('4')]])await test('Leave '+n,async p=>{await leaveForm(p);await dates(p);await fn(p);await p.getByRole('button',{name:'Submit request'}).click();await p.getByText('Leave request submitted').waitFor()})
await test('Approve/reject with comments',async p=>{await p.locator('header select').selectOption({label:'HR Admin'});await nav(p,'Approvals');await p.locator('textarea[placeholder="Optional approval comment"]').fill('Review complete');await p.getByRole('button',{name:'Approve'}).click();await p.getByText(/request approved/).waitFor()})
await test('Role switcher',async p=>{let s=p.locator('header select');for(const x of ['Reporting Manager','HR Admin','Employee']){await s.selectOption({label:x});if(await s.inputValue()!==x)throw Error(x+' not selected')}})
await test('Employee drill-down',async p=>{await p.locator('header select').selectOption({label:'Reporting Manager'});await nav(p,'Timesheet');await p.locator('select').nth(1).selectOption('priya');await p.getByText('Priya Shah',{exact:true}).first().waitFor()})
await test('Timesheet search/date filters',async p=>{await nav(p,'Timesheet');await p.getByPlaceholder('Search entries').fill('Design system');if(await p.locator('tbody tr').count()!==1)throw Error('search');await p.locator('input[title="Filter from date"]').fill('2024-11-20');if(await p.locator('tbody tr').count()!==0)throw Error('date')})
await test('Leave search/type/date filters',async p=>{await nav(p,'Leave');await p.getByPlaceholder('Search by name').fill('Alex');await p.locator('select[title="Filter leave by type"]').selectOption('personal');await p.locator('input[title="Filter leave from date"]').fill('2024-11-01');if(await p.getByText('personal',{exact:true}).count()!==1)throw Error('leave filters')})
await test('Approvals search/status/date filters',async p=>{await p.locator('header select').selectOption({label:'HR Admin'});await nav(p,'Approvals');await p.getByPlaceholder('Search by name').fill('Alex');await p.locator('select[title="Filter approvals by status"]').selectOption('pending');await p.locator('input[title="Filter approvals from date"]').fill('2024-11-01');if(await p.getByText('Alex Morgan',{exact:true}).count()===0)throw Error('approval filters')})
await test('Mobile drawer open/close',async p=>{await p.setViewportSize({width:390,height:844});await p.reload({waitUntil:'domcontentloaded'});await p.waitForTimeout(500);await p.locator('header button').first().click();await p.locator('aside.fixed').waitFor();await p.locator('div.fixed.inset-0').click({position:{x:10,y:10}});if(await p.locator('aside.fixed').count())throw Error('drawer stayed open')})
for(const x of results)console.log(x.join(' | '));console.log(`TOTAL ${results.length} | PASSED ${results.filter(x=>x[0]==='PASS').length} | FAILED ${results.filter(x=>x[0]==='FAIL').length}`);await browser.close()
