export const workflowRoutes = (
  app,
  send,
  requireCapability,
  transitionHandler,
  service,
) => {
  app.post(
    "/api/v1/attendance-sessions/clock-in",
    requireCapability("attendance:write"),
    send(service.clockIn, 201),
  );
  app.post(
    "/api/v1/attendance-sessions/clock-out",
    requireCapability("attendance:write"),
    send(service.clockOut),
  );
  const transitions = [
    [
      "leave-requests",
      "submit",
      "leave:write",
      "draft",
      "pending",
      "leave_submit",
    ],
    [
      "leave-requests",
      "withdraw",
      "leave:write",
      "pending",
      "withdrawn",
      "leave_withdraw",
    ],
    [
      "leave-requests",
      "cancel",
      "leave:write",
      "approved",
      "cancelled",
      "leave_cancel",
    ],
    [
      "leave-requests",
      "approve",
      "leave:approve",
      "pending",
      "approved",
      "leave_approve",
    ],
    [
      "leave-requests",
      "reject",
      "leave:approve",
      "pending",
      "rejected",
      "leave_reject",
    ],
    [
      "leave-requests",
      "force-approve",
      "leave:override",
      "pending",
      "approved",
      "leave_force_approve",
    ],
    [
      "attendance-adjustments",
      "submit",
      "attendance:write",
      "draft",
      "pending",
      "adjustment_submit",
    ],
    [
      "attendance-adjustments",
      "withdraw",
      "attendance:write",
      "pending",
      "withdrawn",
      "adjustment_withdraw",
    ],
    [
      "attendance-adjustments",
      "approve",
      "attendance:approve",
      "pending",
      "approved",
      "adjustment_approve",
    ],
    [
      "attendance-adjustments",
      "reject",
      "attendance:approve",
      "pending",
      "rejected",
      "adjustment_reject",
    ],
    [
      "alerts",
      "acknowledge",
      "alerts:write",
      "open",
      "acknowledged",
      "alert_acknowledge",
    ],
    [
      "alerts",
      "resolve",
      "alerts:write",
      "acknowledged",
      "resolved",
      "alert_resolve",
    ],
  ];
  for (const [
    resource,
    action,
    capability,
    expected,
    next,
    audit,
  ] of transitions)
    app.post(
      `/api/v1/${resource}/:id/${action}`,
      requireCapability(capability),
      transitionHandler(resource, expected, next, audit),
    );
};
