import test from "node:test";
import assert from "node:assert/strict";
import {
  schema,
  validateEntity,
} from "../../src/server/validation/schema-validator.js";

const fields = {
  Tenant: [
    "tenant_id",
    "name",
    "timezone",
    "locale",
    "week_start",
    "currency",
    "settings",
  ],
  User: [
    "user_id",
    "tenant_id",
    "employee_id",
    "display_name",
    "email",
    "capabilities",
    "status",
  ],
  Employee: [
    "employee_id",
    "tenant_id",
    "employee_number",
    "name",
    "job_id",
    "manager_id",
    "department_id",
    "location_id",
    "holiday_calendar_id",
    "work_schedule",
    "start_date",
    "status",
  ],
  Department: ["department_id", "tenant_id", "name", "code", "status"],
  Location: [
    "location_id",
    "tenant_id",
    "name",
    "timezone",
    "holiday_calendar_id",
    "status",
  ],
  WorkSchedule: [
    "schedule_id",
    "tenant_id",
    "name",
    "weekday_rules",
    "effective_from",
    "effective_to",
    "status",
  ],
  JobProfile: [
    "job_id",
    "tenant_id",
    "title",
    "department_id",
    "standard_daily_mins",
    "standard_weekly_mins",
    "is_ot_eligible",
    "max_daily_mins",
    "effective_from",
    "effective_to",
    "status",
  ],
  AttendanceSession: [
    "session_id",
    "tenant_id",
    "employee_id",
    "clock_in_at",
    "clock_out_at",
    "source",
    "status",
    "version",
  ],
  AttendanceSummary: [
    "summary_id",
    "tenant_id",
    "employee_id",
    "local_date",
    "worked_mins",
    "scheduled_mins",
    "overtime_mins",
    "status",
    "exception_codes",
    "effective_job_id",
  ],
  AttendanceAdjustment: [
    "adjustment_id",
    "tenant_id",
    "employee_id",
    "local_date",
    "original",
    "proposed",
    "reason",
    "attachment_ids",
    "status",
    "submitted_at",
    "decided_by",
    "decided_at",
    "decision_note",
    "version",
  ],
  LeaveType: [
    "leave_type_id",
    "tenant_id",
    "name",
    "code",
    "unit",
    "is_paid",
    "color",
    "description",
    "status",
  ],
  JobLeavePolicy: [
    "policy_id",
    "tenant_id",
    "job_id",
    "leave_type_id",
    "annual_allotment",
    "accrual_rule",
    "carry_over_limit",
    "allow_negative",
    "allow_partial_day",
    "counting_rule",
    "request_window",
    "documentation_rule",
    "effective_from",
    "effective_to",
    "status",
  ],
  LeaveBalance: [
    "balance_id",
    "tenant_id",
    "employee_id",
    "leave_type_id",
    "period",
    "accrued",
    "carried_over",
    "manual_adjustments",
    "used",
    "pending",
    "remaining",
    "unit",
    "as_of",
  ],
  LeaveLedgerEntry: [
    "entry_id",
    "tenant_id",
    "employee_id",
    "leave_type_id",
    "effective_date",
    "amount",
    "entry_type",
    "source_id",
    "reason",
    "created_by",
    "created_at",
  ],
  LeaveRequest: [
    "request_id",
    "tenant_id",
    "employee_id",
    "leave_type_id",
    "start_date",
    "end_date",
    "partial_day",
    "partial_start_time",
    "partial_end_time",
    "partial_minutes",
    "chargeable_amount",
    "reason",
    "attachment_ids",
    "status",
    "approver_id",
    "submitted_at",
    "decided_at",
    "decision_note",
    "version",
  ],
  OvertimeRequest: [
    "overtime_request_id",
    "tenant_id",
    "employee_id",
    "local_date",
    "start_time",
    "end_time",
    "requested_mins",
    "reason",
    "status",
    "approver_id",
    "submitted_at",
    "decided_at",
    "decision_note",
    "version",
    "created_at",
  ],
  Attachment: [
    "attachment_id",
    "tenant_id",
    "owner_type",
    "owner_id",
    "file_name",
    "mime_type",
    "size_bytes",
    "mock_url",
    "validation_status",
  ],
  HolidayCalendar: [
    "holiday_calendar_id",
    "tenant_id",
    "name",
    "location_ids",
    "status",
  ],
  Holiday: [
    "holiday_id",
    "tenant_id",
    "holiday_calendar_id",
    "name",
    "local_date",
    "observance_type",
    "description",
    "status",
  ],
  Alert: [
    "alert_id",
    "tenant_id",
    "employee_id",
    "type",
    "severity",
    "period_start",
    "period_end",
    "current_mins",
    "threshold_mins",
    "created_at",
    "status",
  ],
  AuditEvent: [
    "event_id",
    "tenant_id",
    "actor_user_id",
    "actor_role",
    "action",
    "target_type",
    "target_id",
    "occurred_at",
    "reason",
    "metadata",
  ],
};

test("canonical schema contains exactly the documented entities and fields", () => {
  assert.deepEqual(
    Object.keys(schema.$defs).sort(),
    Object.keys(fields).sort(),
  );
  for (const [entity, expected] of Object.entries(fields)) {
    assert.deepEqual(Object.keys(schema.$defs[entity].properties), expected);
    const optional = entity === "LeaveRequest" ? new Set(["partial_start_time", "partial_end_time", "partial_minutes"]) : new Set();
    assert.deepEqual(schema.$defs[entity].required, expected.filter((field) => !optional.has(field)));
  }
});

test("validator rejects unknown and missing fields", () => {
  assert.throws(() => validateEntity("Tenant", { tenant_id: "t" }), /required/);
  assert.throws(
    () =>
      validateEntity("Tenant", {
        tenant_id: "t",
        name: "T",
        timezone: "UTC",
        locale: "en",
        week_start: 1,
        currency: "USD",
        settings: {},
        extra: true,
      }),
    /not part/,
  );
});
